### ISSUE TITLE
如何刮削115网盘挂载到虚拟盘的视频

### ISSUE THREAD

**Issue by jiangbao1260** [CineMingle/CineMingle#6]
![1704931289129](https://github.com/CineMingle/CineMingle/assets/156298016/49cfa66b-cd21-4397-842d-ac21aee02fe0)
![1704931336327](https://github.com/CineMingle/CineMingle/assets/156298016/31347912-ab56-47da-adb4-ef8fcb8e8c97)
![1704931801783](https://github.com/CineMingle/CineMingle/assets/156298016/f76fc07c-2cd3-426b-a9a7-34c4920c44b3)
![1704962120455](https://github.com/CineMingle/CineMingle/assets/156298016/8a6d0e95-b9d1-46b7-ab24-b413a810ea0c)

**Comment by CineMingle** [comment]
第三张图里面文件夹是什么样子？里面还套文件夹么？可以方便再截图么？
想看下目录树大概什么样子

**Comment by jiangbao1260** [comment]
![1705073471914](https://github.com/CineMingle/CineMingle/assets/156298016/afdaa6f1-b79c-48ba-ae54-14359e2a06ed)
![1705073915839](https://github.com/CineMingle/CineMingle/assets/156298016/6b03ea7d-4aef-4df8-9801-0b4741196fc6)
我比较懒，贪方便就直接把同一个老师的资源都丢在一个文件夹里了，不过按每一部资源在老师的文件夹里再细分出一个文件夹emby也能读取

**Comment by CineMingle** [comment]
1.2.0 发布应该支持115了。谢谢支持！
